name: GitHub Actions Demo
run-name: ${{ github.actor }}'s banger work flow'
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: |
          # build image
          docker build -t enoch-test-blazor-thing .

          # run image
          docker run -d\
          -p 3252:7856 --name "enoch-test-blazor-thing"\
          enoch-test-blazor-thing

          echo "made it to the end ╰(▔∀▔)╯ "